### ISSUE TITLE
Ability to pick time?

### ISSUE THREAD

**Issue by yongzhihuang** [wojtekmaj/react-date-picker#10]
Hi, Thanks for taking over this project.  I'm a user of the former library, and was able to pick time along with date.  In this version i'm unable to do so, apologize in advance if this was documented somewhere but can you tell me how I can do this?

**Comment by wojtekmaj** [comment]
Hey @yongzhihuang!
I have a very busy period in my personal life but I think it is a great idea and it's definitely on my list. If you really need to have this feature right now, I'd suggest keeping an old version. I'll keep you updated if I have any news about this!
Cheers,
Wojciech

**Comment by yongzhihuang** [comment]
No problem @wojtekmaj thanks for keeping this project going.  I will try to contribute to this when I have time too.

**Comment by wojtekmaj** [comment]
Actually, my plan is to create another repo just like I did for the calendar which react-date-picker uses under the hood. After that, I'll use it in react-date-picker. I believe that in this way, I can benefit much more people and at the same time, because of having everything physically separate, keep the structure much more ordered and robust.

**Comment by wojtekmaj** [comment]
Quick update on progress: [react-clock](https://github.com/wojtekmaj/react-clock) repository was created, I'm currently building and documenting UI for the clock for time picking.

**Comment by wojtekmaj** [comment]
Hi @yongzhihuang!
Coming back to you with good news. [React-DateTime-Picker](https://github.com/wojtekmaj/react-datetime-picker) just got out and it should be just what you need!
Let me know what you think!
