### ISSUE TITLE
Clicking on "input group", but not in an input, does nothing.

### ISSUE THREAD

**Issue by baleeds** [wojtekmaj/react-date-picker#114]
It seems to me that the UX would greatly improved if there were some reaction when clicking in the styled 'input' area, marked by the class "react-date-picker__button__input".  This is very evident when inputs are taking the whole width:

![image](https://user-images.githubusercontent.com/9682964/47916432-99a77680-de7c-11e8-92c8-60d8c8cc067e.png)

My expectation is that clicking in that area would focus the first text input.

**Comment by nkurapati** [comment]
Small work around

`
.react-date-picker__inputGroup__year {
        flex-grow: 1;
      }
}
`

**Comment by wojtekmaj** [comment]
Yeah that seems like a neat idea. It's what native input does by default when expanded beyond what's necessary, and React-Date-Picker's aim is to behave as closely to a native input as possible. This will be out with the next release of React-Date-Picker, React-DateTime-Picker, React-Time-Picker and their range versions, too.

**Comment by baleeds** [comment]
Looking forward to it!  Thanks for all your work!

**Comment by htmlboy** [comment]
Hi, I'm adding this note for future reference, since I found a workaround for this issue.

You can create a state for `isOpen` and change it by clicking on the DatePicker component. The `isOpen`prop only affects the component when the value change, so it doesn't override other behaviours, like clicking out. BUT for the same reason, you should update the state when the calendar is closed, or it will only work once.

Here's my code.

Before `render()`: 

```
constructor() {
    super();
    this.state = {
      isOpen: false,
    };
    this.openCal = this.openCal.bind(this);
    this.closeCal = this.closeCal.bind(this);
  }

  openCal() {
    this.setState({ isOpen: true });
  }

  closeCal() {
    this.setState({ isOpen: false });
  }

```

On the `DatePicker` component:

```
<DatePicker
          onCalendarClose={this.closeCal}
          onClick={this.openCal}
          isOpen={this.state.isOpen}
          …
/>
```

(Potential workaround for #120 #67 and related to #59)
