### ISSUE TITLE
Allow prop to determine if date is required

### ISSUE THREAD

**Issue by jtwhittington** [wojtekmaj/react-date-picker#16]
Currently the inputs for the date-picker are hard-coded as being required. Would you be interested in allowing a prop to determine if the date is required or not?

Only reason I am not just making a PR - I found when not required, the inputs are filled out automatically once you enter a single value (day, month, or year) and also its basically impossible to clear the date.

I'd be happy to dig into it more.

**Comment by wojtekmaj** [comment]
Hmmm. That's a little tough indeed. I currently have no time to dig into this, but I guess it is a very needed enhancement.

I believe that onChangeExternal function would be the one to be changed in order to validate. Currently, we're running native `.checkValidity()` on each field (day, month, year). Changing it so that it also validates on its own whether all fields are filled in would be a good addition allowing us to change `required` flag via props.

That also has drawn my attention that there's no clear button... Looks like a lot of great ideas. Now let's hope this weekend will be a calm one...!

**Comment by wojtekmaj** [comment]
Hey @jtwhittington,
Version 6.4.0 just went out and you can now have fields not required. All the side effects you were writing about were elliminated. Please let me know what you think!
