### ISSUE TITLE
Open calendar only when clicking on icon

### ISSUE THREAD

**Issue by emiliano-mongelo** [wojtekmaj/react-date-picker#175]
Hi. I'm trying to open the calendar only if the calendar icon is clicked but not on input click. As it is mentioned in #59 `isOpen` prop doesn't work. 
Anyone found other solution?

**Comment by thadk** [comment]
This is happening to me on Firefox `72.0b8` and stable on macOS only. If I use the DOM inspector to move the element outside of the page (and Styled components) then it starts to work.

You can try and see the problem here: https://deploy-preview-107--windfall-develop.netlify.com/prescreen-1a/

*Update: I thought this was fixed but I just inadvertently used Chrome instead of macOS Firefox*

Here are screencasts:
Chrome and Windows FF work fine:
![date-picker-ff-macbug](https://user-images.githubusercontent.com/283343/75313806-f83ff300-582b-11ea-8d2c-df163bd92526.gif)

Mac Firefox cannot use the open picker unless it was opened using the icon.

**Comment by thadk** [comment]
This now seems fixed!

**Comment by wojtekmaj** [comment]
Duplicate of #284 

Implemented in #362 in a form of new `openCalendarOnFocus` prop which can be explicitly set to `false` to achieve desired behavior.

**Comment by framirezsandino** [comment]
@wojtekmaj it seems `openCalendarOnFocus` is not used on `onInputClick`, so, It doesn't consider focus bring on input click. Is there a way to disable opening calendar on input click and allowing it to open it only via icon click?
