### ISSUE TITLE
Month Select option doesn't show which month is selected

### ISSUE THREAD

**Issue by TsepoNtsaba** [wojtekmaj/react-date-picker#196]
First of all, awesome work on the react date picker. I'm running automation tests and I need to validate the date the user sees on the front end. 

<img width="397" alt="Screenshot 2019-09-27 at 15 43 13" src="https://user-images.githubusercontent.com/4621048/65773985-a6405780-e13d-11e9-8155-01c62b09c62a.png">

So far I have no issues with doing that for the day and year, but since month is a dropdown, I can't validate the month the user sees on the front end, because the dropdown option doesn't have a selected attribute for the month displayed.

<img width="684" alt="Screenshot 2019-09-27 at 15 43 38" src="https://user-images.githubusercontent.com/4621048/65774001-ae989280-e13d-11e9-8aa4-70f4dc58f0a7.png"> 

Is there a way I can validate which month is selected/displayed on the dropdown options?

**Comment by wojtekmaj** [comment]
Uh, oh. For compatibility reasons React, instead of using this selected attribute, uses a value attribute on the root select tag.

I suggest using [HtmlSelectElement.selectedOptions](https://developer.mozilla.org/en-US/docs/Web/API/HTMLSelectElement/selectedOptions) to get the list (1 element long, obviously) of selected options.
