### ISSUE TITLE
Calendar should open on month containing minDate when date picker has no value.

### ISSUE THREAD

**Issue by kjarbr** [wojtekmaj/react-date-picker#209]
Calendar default opens on month containing current date. It should instead show month containing min date.

**Comment by alicerocheman** [comment]
minDate, maxDate... anything but a date outside of the boundaries would be good!

**Comment by wojtekmaj** [comment]
You're correct - by calendar should default to selected date or today's date, limited by minDate and maxDate.

For now, you can use `activeStartDate` to override default displayed month.

**Comment by arpitprod** [comment]
After added `activeStartDate`, I can't change calendar's month or year 

https://user-images.githubusercontent.com/19798516/118395050-ed0df880-b665-11eb-9d5b-321cff8bcc05.mov

**Comment by WillJiCar** [comment]
This issue is still happening, adding activeStartDate breaks the back and next buttons on the calendar. 

I had to put in a hacky workaround. I'm using Formik with the date field being null initially (and so the calendar is blank on load) - when the component loads it creates a useState which stores this initial value (either null, or a date). 

`const [date, setDate] = useState(field.value) //Will grab whatevers in initialValues (date or null). This is how we'll control the temporary date state if the initialValue is null.`

`onChange={(e) => { field.setFieldValue("Date", e) } //This will only trigger if a date is physically entered by a user, so will not be triggered by changing the date state`

`onCalendarOpen={() => { if(date == null){ setDate(maxDate) }  //Temporarily set the date to the max date so the calendar jumps to it if the initialValue is null.`

`onCalendarClose={() => { if( formikDateIsNull ){ setDate(null) } //Luckily setting the value using state does not trigger the onChange method, allowing for us to check if the user changed the date from the temporary value`

`value={date} //Either formik value (null or date) or our temporary value (maxDate)`

**Comment by mariusrak** [comment]
Hi, I also encountered this. Could this be fixed? I tried the `activeStartDate` workaround, but that didn't work.
