### ISSUE TITLE
Timezone Changes Date Chosen

### ISSUE THREAD

**Issue by AustinMutschler** [wojtekmaj/react-date-picker#222]
Hello, when I store the data in JSON in MongoDB then feed that date back into the date picker it changes the date based on the timezone it was initially set in.

For example, if someone on the East coast sets the date as 01/14/2020 and then someone on the West coast of the United States looks at the date, it will say 01/13/2020. Conversely if someone on the West coast sets the date, the person on the East coast sees the same date because they are ahead in time and not behind.

How can I set the date picker to set a static timezone so that the date is the same regardless of who is looking at it?

**Comment by wojtekmaj** [comment]
React-Date-Picker lets users pick local time. So if you're sitting in London, 2020-01-14 will be exactly 2020-01-14 Midnight. But in Berlin, UTC+1, date picked will be Berlin's local midnight, which is 2020-01-13T23:00:00 UTC. In order to save UTC date, you would need to convert the date to UTC by yourself, for example:

```
const dateUtc = new Date(`${date.getFullYear()}-${date.getMonth() + 1}-${date.getDate()}`)
```

This way you're making a new Date object from a string that gets interpreted as ISO date.

**Comment by julianpetriv** [comment]
If you need only string with date this variant worked for me: `date.toDateString()`
