### ISSUE TITLE
Sometime component overload CPU and tab crashes

### ISSUE THREAD

**Issue by repjov** [wojtekmaj/react-date-picker#318]
The date-picker component being used crashes on Firefox/Chrome on Linux and Windows (Upd: For MacOS the same for Safari/Chrome).

**How to catch this up**
I have several datepickers on the page, and if I randomly pick dates in each input in some moment it stop works at all, and the tab crashes.

**Comment by wojtekmaj** [comment]
Are you able to create a reproducible demo on CodeSandbox?

**Comment by repjov** [comment]
> Are you able to create a reproducible demo on CodeSandbox?

Sure I will try.

**Comment by lagroms** [comment]
I'm having the same issue. In some places of my app, the component works just fine, and on 1 specific page, clicking on the component makes the CPU go 100% and them the browser is unresponsive. I don't understand what's the reason behind this because i'm using it in the exact same manner as the rest of my pages.
