### ISSUE TITLE
react-date-picker falls below inputs in bootstrap forms on small screens

### ISSUE THREAD

**Issue by Omortis** [wojtekmaj/react-date-picker#32]
Hello,

Nice component, it works very well. However at smaller breakpoints the component itself seems to drop below other inputs? Possibly a z-index issue? See attached.

This is a fairly vanilla Bootstrap 3 form layout.

Not sure where to start to debug it. Any suggestions?

react 16.2.0
react-date-picker 6.5.2

Thanks!

John

<img width="681" alt="date-picker" src="https://user-images.githubusercontent.com/14285373/34084980-3338244c-e357-11e7-9647-47f33868c628.png">

**Comment by wojtekmaj** [comment]
Hey!
It seems like you have some elements that are, just like the calendar in React-Date-Picker, positioned using `position: relative` or `absolute`.

There can be two cases:

1. They cover the calendar because both calendar and elements covering it have no `z-index` value set. In this case, elements that come after calendar in HTML structure will cover it. Apply `z-index: 1` to `.react-date-picker__calendar`.
2. Elements covering the calendar have some `z-index` value set and because of that calendar is covered.
Check how big is `z-index` value of elements covering the calendar. Apply `z-index` with a value higher than in elements covering to `.react-date-picker__calendar`.

**Comment by Omortis** [comment]
Will check ASAP. Ran out of time but will be back on Wednesday.

**Comment by wojtekmaj** [comment]
No problem. I'll be happy to reopen if you'd still need help!

**Comment by Omortis** [comment]
@wojtekmaj: setting z-index (option #1 above) worked fine - thanks!

**Comment by yoondaeyoung** [comment]
@wojtekmaj:  Bear with me, I used `z-index` in higher number such as `9999` for `.react-date-picker__calendar` however when my browser is in small scale its top portion is cut off but when I expand it in full then it displays full calendar widget.  Any suggestion and advice, you could share with me? Unfortunately I am a novice react developer who just got my feet wet on this and I am not sure how to correct this problem. Ty for your time!

**Comment by holmesjr** [comment]
This is still an issue, even when I've set `z-index 9999 !important` on a number of the divs in the CSS. I'm not using bootstrap, I'm using native-base on web.
