### ISSUE TITLE
controlled datepicker still allowing displayed year to be uncontrolled

### ISSUE THREAD

**Issue by jonathanSimonney** [wojtekmaj/react-date-picker#322]
Hello, and thank you very much for still maintaining this amazing npm package.

I think the controlled way of using it has a bug, as reproduced on this video : https://www.loom.com/share/2b74bca8f1974fe6bf346d1aeec0f8e8 (it's only 15 seconds long).

The codesandbox where I did it is https://codesandbox.io/s/try-reproduce-controlled-datepicker-bug-uj68z?file=/src/App.js.

As you can see, the input is supposedly controlled, as to only allow for the first four digits of the year to be taken into account, but when you enter a year by hand, it still displays the numbers you wrote, even if they're the fifth or sixth number. From what my devtools in my project showed, the value passed DOES respect the controlled value (i.e, it is in the example only the first four digits), but the displayed value is still wrong.

(for my project, I'll probably use the maxYear to achieve what I need, but I nevertheless think this is a bug, and I hope reporting it will be of some help.)

Hoping this won't be a duplicate, and thanking you again for the work you put into this package. Have a nice day.

**Comment by wojtekmaj** [comment]
Hi - sorry for a major delay in replying....

Making this component _fully_ controlled wouldn't be possible, because WIP state (separate for day, month, year...) is not exposed. Rather, a valid date is returned in onChange and accepted back in value. So instead, onChange fires whenever a valid date is written in full - similarly to how native date input works - and allows it being updated using value prop change.
