### ISSUE TITLE
Get output in the defined format

### ISSUE THREAD

**Issue by gurmeetsinghmalhotra** [wojtekmaj/react-date-picker#348]
I have two issues 

1) I have set the format of my calendar to "y-MM-dd". Is there a way to access the value selected by the user in the same format?
2) Currently user is able to change the date through the input field by using arrow keys as well as Calendar. Is there a way to restrict users only to change the date through the calendar and none other?

**Comment by wojtekmaj** [comment]
1. No there is not. However this format is compatible with date-fns format, so you can pass format to both React-Date-Picker and format() from date-fns (along with the Date() of course) to achieve the result you need.

2. I'd check what happens when you use `disabled` prop (don't remember, on mobile), or simply build a component wrapping React-Calendar yourself if you don't need React-Date-Picker core functionality.
