### ISSUE TITLE
Add ability to return an ISO date string

### ISSUE THREAD

**Issue by ro-savage** [wojtekmaj/react-date-picker#4]
It would be great to return the date as a string, or as a Date().

Date() has a bunch of weird issues around it that can randomly bite people in the butt.

As the datepicker only returns a date, if it could (optionally) be returned as in the [ISO date format](https://en.wikipedia.org/wiki/ISO_8601) `YYYY-MM-DD` it would allow developers to figure out how they wanted to handle the date.

My specific use case, we just care about the date and location. That data is then sent to the server which uses a proper date implementation to give us the correct timezones, offsets, daylight savings etc.

Another use case, is someone could convert it to a moment object on the frontend.

**Comment by wojtekmaj** [comment]
Hey @ro-savage,
sadly people have tons of use cases and it would be hard to satisfy all; probably that would end in onChange sending 14 parameters along ;)

The good news is, you can get an ISO date from Date() pretty easily:

```js
onChange = (date) => {
    const ISOdate = date.toISOString();
    // do stuff with ISOdate
}
```

One thing to remember in order to avoid confusion is to always remember that the user picks their local date. So, unless placed around London, ISO calendar date may differ from the one chosen by the user.
If you need to get ISO-like format of user's chosen local date, you can use this function or similar:

https://github.com/wojtekmaj/react-date-picker/blob/master/src/shared/dates.js#L43-L60
