### ISSUE TITLE
Add `calendarProps` prop

### ISSUE THREAD

**Issue by wojtekmaj** [wojtekmaj/react-date-picker#400]
### Before you start - checklist

- [X] I have checked if this feature request is not already reported

### Description

Currently, calendar consumes all props with a few exceptions:

https://github.com/wojtekmaj/react-date-picker/blob/5f11efba15c47d854668527ceb9e56bd897c7aaf/src/DatePicker.jsx#L234-L240

This limits the possibilities of how React-Date-Picker and React-Calendar could be customized. #399 would be an example.

### Proposed solution

Allow even more powerful customizations by adding `calendarProps` object which, you've guessed it, would contain all props that shall be passed to React-Calendar.

**Comment by chriscarrillo** [comment]
@wojtekmaj Thank you for this. I believe this would be a great feature to add!

I have set a `minDate` and `maxDate` with a default value of `undefined` but when I open the calendar, today's date shows by default. I would like the `minDate` to be the default date that shows when the calendar opens. If a `minDate` is set, I propose the calendar shows that date as the default date instead of today's date.

Nevertheless, if the default date behavior stays the same, since `react-calendar` has a prop for `defaultActiveStartDate`, would this change allow me to set the default date that is shown when the calendar is opened?

**Comment by wojtekmaj** [comment]
Done in fdc0d92e7d04fae8e669cd99e5cafe8f7019c569
