### ISSUE TITLE
How to define a period range as 'week', 'month', 'year' ?

### ISSUE THREAD

**Issue by m41w4r3exe** [wojtekmaj/react-date-picker#63]
Hi, thanks for the great lib! I’d like to ask if it is possible to be able to select a predefined period range as ’week’, ‘month’, ‘year’? Some example pics might help what I’m trying to say. I couldn’t find a way to implement such thing with your calendar, would love to hear from you if it is possible? I can see a way of implementing it for month and year through determining the maxDetail props with another button but I can't see a way for selecting week? Thanks for any help.
![screen shot 2018-04-06 at 17 16 38](https://user-images.githubusercontent.com/33025255/38426802-48275566-39c0-11e8-8b7b-1d8e7e849779.png)
![screen shot 2018-04-06 at 17 16 48](https://user-images.githubusercontent.com/33025255/38426804-4899abf2-39c0-11e8-84df-e0bc684c67dc.png)
![screen shot 2018-04-06 at 17 16 57](https://user-images.githubusercontent.com/33025255/38426805-48beb960-39c0-11e8-8088-76088237a200.png)

**Comment by wojtekmaj** [comment]
Hey,
you're looking for [react-daterange-picker](https://github.com/wojtekmaj/react-daterange-picker/) :)

**Comment by m41w4r3exe** [comment]
Thanks for the reply, but I still couldn't find a way with that lib you mentioned, to implement week range selection as shown in the first screenshot.

**Comment by wojtekmaj** [comment]
Ah, sorry, now I get what you meant. I'm afraid you can't select other things than:

* days on month view
* months on year view
* years on decade view
* decades on century view

This is a hard case :( I don't think that picker will do the job very well. If you must, what you could do is disable all days but sundays and use some CSS to style it so that the whole week is covered by Sundays (or whatever the last day of the week is in your case). To do that:

* use tileDisabled prop to disable everything but Sundays
* use tileClassName to attach some class name to Sundays
* use CSS like `margin-left: -80%; padding-left: 80%` to extend Sundays clickable area
* (optionally) use CSS like `pointer-events: none;` on all days but Sundays to make them "transparent" for clicks
