### ISSUE TITLE
Highlight on today

### ISSUE THREAD

**Issue by brunaprestes** [wojtekmaj/react-date-picker#71]
It's nice have the current date with another color different of the selected date and the other days

**Comment by wojtekmaj** [comment]
Hey there, 
you can pass any [react-calendar](https://github.com/wojtekmaj/react-calendar) prop to `DatePicker`. `tileClassName` is what you're looking for, only you need to have a function `isToday` which you'll use, and make sure you only use it on month view (otherwise you might get colored month tiles or year tiles). An example from documentation gives all wednesdays `wednesday` class:
```js
({ date, view }) => view === 'month' && date.getDay() === 3 ? 'wednesday' : null
```
Then, you can style the tile however you want, have a different font, border, shadow, you name it :)

**Comment by wojtekmaj** [comment]
I'm closing this to give issues that require my attention more visibility. Happy to reopen if you need more assistance.
