### ISSUE TITLE
Allow MMM & MMMM in format

### ISSUE THREAD

**Issue by douglascantomelo** [wojtekmaj/react-date-picker#83]
How set format date to "Jan 2018" for example?
```
            <DatePicker
              onChange={this.onChange}
              value={this.state.date}
              locale="pt-br"
              maxDetail="year"
            />
```

**Comment by Anlh** [comment]
I would also like to know if it's possible to change the current output format

**Comment by wojtekmaj** [comment]
No, you can't do that at the moment. This is because currently all the fields are numeric and although it would be easy to implement _displaying_ the date in "Jan 2018" format, saving it back to an actual `Date()` would be highly problematic. I explained a little more about `locale` approach in #90. I'd need to implement it in a form of a dropdown, but this way the date will not be easily written using the keyboard.

BTW you should have written `locale="pt-BR"`, it's case sensitive :)

**Comment by isab** [comment]
+1 to this. It would be really helpful to be able to just display the month name at least.

**Comment by wojtekmaj** [comment]
By popular demand... :> Both MMM (short month name) and MMMM (long month name) will be supported.

<img src="https://user-images.githubusercontent.com/5426427/60820651-3af18400-a1e5-11e9-9b19-211df5db0d8f.png" width="387" />

**Comment by isab** [comment]
@wojtekmaj Since this isn't part of a release yet, how would I use this in my app right now? Thanks!

**Comment by wojtekmaj** [comment]
@isab It shouldn't take long for the next release, some manual testing remaining and that's all. Hold tight!
