### ISSUE TITLE
accept placeholder text

### ISSUE THREAD

**Issue by gengue** [wojtekmaj/react-date-picker#86]
The UI of my website is based in placeholders instead labels but the date input puts automatically a localized placeholder with the date format like this `--/--/---`  which is great but it's not a suitable behavior for all cases. I would like to pass a `placeholder` prop to overwrite the default like a normal text input.

that's make sense for you?

Thanks in advance

**Comment by wojtekmaj** [comment]
Duplicate of #6

**Comment by gengue** [comment]
@wojtekmaj this is not the same as #6 , actually it's a consequence of that thread. I want to display my placeholder (words) instead a date format placeholder.

e.g

```
<DatePicker
  onChange={this.onChange}
  value={this.state.returnDate}
  placeholder="Return flight date"
/>
```

![renderExample](https://user-images.githubusercontent.com/2824293/43907443-0c71c788-9bbb-11e8-899a-df8b6e5a9736.png)

**Comment by wojtekmaj** [comment]
Ooh! Sorry and thanks for clarification.

I don't think that could be easily done though. The reason is that date picker actually consists of several inputs, one for each number, separated by - or /.

The only thing that comes up to my mind is to make absolutely placed pseudoelement with `pointer-events: none;`and remove it on focus. This however has some disadvantages too: you never know if the user will be able to click though and land on an actual input field (clicking on a separator does nothing) and the user would be very likely to click the middle field. You would need to hack your way around by expanding the first field do that the user always clicks it. So I'd discourage this approach, unless you're willing to go for CSS wizardry.
