### ISSUE TITLE
Setting a different date format

### ISSUE THREAD

**Issue by duncanmwirigi** [wojtekmaj/react-date-picker#90]
How can one implement different date format

**Comment by wojtekmaj** [comment]
Hello,
React-Date-Picker takes a little different approach. This is because React-Date-Picker is so much more than just the format. For instance, calendar will also adapt and show Saturday, Sunday or Monday first, different workdays, etc.

For instance, if you would like to have DD.MM.YYYY, you'll get it if you choose a `locale` of a country that usually formats the date this way, so for example `"en-GB"` would work. If you leave it undefined, it will show your user's native locale!

**Comment by Randore** [comment]
I have set it to locale="en-US" but my date is formatted as 2018-08-27T18:30:00.000Z
How to format it so that it save and edit form as MM/DD/YYYY

**Comment by wojtekmaj** [comment]
@Randore You should pass an instance of `Date()` to `value` prop, so `value={new Date('2018-08-27T18:30:00.000Z')}` should work for you.

**Comment by Randore** [comment]
Sorry but I would like to know how to use this with formik.
1. I have created a `<DatePicker value={this.props.value}  />` component which I am importing into formik and passing values using.
`<FormControl values={values.price} onChange={setFieldValue}  />`

There is some more code which I can't post here.

I think the problem is saving in string date format and need to convert string into object to be able to select from calendar.

**Comment by wojtekmaj** [comment]
This seems like a separate issue so please don't post here as it notifies all the people who are interested in date formatting from the first post. If anything, please raise another issue.

Regarding Formik, I haven't used this package, so you could probably ask for their support as well.

**Comment by wojtekmaj** [comment]
Hi,
just a heads up that newest versions of React-Date-Picker support `format` prop, so you should be able to set a different format. Please remember that `locale` is still needed to display proper calendar picker, so treat `format` as an enhancement, and not `locale`'s replacement.

You'll find more details on `format` prop in README.
